version: '3.7'

services:
  runner:
    image: runner:${TAG:-latest}
    environment:
      - JOB=TestJob
      - TEST_ENDPOINT_BASE_URL=https://sample-service.com/
    build:
      context: .
      dockerfile: Runner/Dockerfile