version: '3.7'

services:
  runner:
    image: runner:${TAG:-latest}
    environment:
      # specify the job type to execute
      - JOB=TestJob
      # add other configuration variables
      - TEST_ENDPOINT_BASE_URL=https://sample-service.com/
    build:
      context: .
      dockerfile: Runner/Dockerfile